### ISSUE TITLE
The 2.1.2 release tarball contains 2.1.1 dll files.

### ISSUE THREAD

**Issue by lopippo** [MatteoLacki/IsoSpec#37]
Greetings, 

this is just to let you know. It does not impact my work.

$ tar tvzf isospec-2.1.2.tar.gz | grep dll
-rwxrwxr-x root/root  11701189 2020-07-14 21:02 IsoSpec-2.1.2/IsoSpecPy/IsoSpecPy/prebuilt-libIsoSpec++-2.1.1-x32.dll
-rwxrwxr-x root/root  14749914 2020-07-14 21:02 IsoSpec-2.1.2/IsoSpecPy/IsoSpecPy/prebuilt-libIsoSpec++-2.1.1-x64.dll

Sincerely,
Filippo

**Comment by michalsta** [comment]
Hi,

This is deliberately so: the 2.1.2 release is R-only (we had to workaround
some CRAN build system bugs, affecting only R), so Python and C++ remain at
2.1.1. This might be confusing because git tags cover the entire
repository, and the entire repo gets included in the autogenerated tarball.
If it helps with packaging process, in future we can do empty releases of
the other (IsoSpec++/IsoSpecPy) parts of the software, (that is, with no
changes at all other than the version bump) to keep things in sync.

**Comment by lopippo** [comment]
Greetings,

Thank you for this answer.

Sincerely,
Filippo
